spring.config.import=optional:file:.env[.properties]

spring.application.name=smart-campus
server.port=${SERVER_PORT:8081}
spring.data.mongodb.uri=${MONGO_URI}

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
app.oauth2.authorized-redirect-uri=${OAUTH2_REDIRECT_URI:http://localhost:5173/oauth2/redirect}

app.bootstrap-admin.enabled=${BOOTSTRAP_ADMIN_ENABLED:false}
app.bootstrap-admin.email=${BOOTSTRAP_ADMIN_EMAIL:}
app.bootstrap-admin.password=${BOOTSTRAP_ADMIN_PASSWORD:}
